repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-yaml
      args:
        - --unsafe
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/python-poetry/poetry
  rev: 1.8.0
  hooks:
    - id: poetry-check
    - id: poetry-lock
    - id: poetry-export
    - id: poetry-install
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.4.8
  hooks:
    # Run the linter.
    - id: ruff
      args:
        - --fix
      # Run the formatter.
    - id: ruff-format
- repo: local
  hooks:
    - id: mypy
      name: mypy
      entry: poetry run mypy . --non-interactive
      language: system
      types:
        - python
      pass_filenames: false
