name: Setup sshd
description: Setup sshd
inputs:
  host:
    required: true
    default: ::1
  port:
    requried: true
    default: 22
  ssh_keygen:
    required: true
    default: true
  ssh_add_id_rsa_into_authorized_keys:
    required: true
    default: true
runs:
  using: composite
  steps:
    - name: Install openssh on Ubuntu
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get install -y openssh-server
        sudo systemctl enable --now ssh

    - name: Enable openssh on Mac OS
      if: runner.os == 'macOS'
      shell: bash
      run: |
        sudo systemsetup -setremotelogin on
        sudo dseditgroup -o create -q "$USER" -t user com.apple.access_ssh

    - name: Update sshd_config
      shell: bash
      run: |
        export SSHD_CONFIG="${{ runner.os == 'macOS' && '/private' || '' }}/etc/ssh/sshd_config"

        cat <<-EOF | sudo tee "$SSHD_CONFIG"
        Include /etc/ssh/sshd_config.d/*
        AddressFamily any
        AuthorizedKeysFile  .ssh/authorized_keys
        ChallengeResponseAuthentication no
        EOF

    - name: Restart sshd - Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo systemctl restart ssh

    - name: Restart sshd - Mac
      if: runner.os == 'macOS'
      shell: bash
      run: |
        sudo launchctl unload /System/Library/LaunchDaemons/ssh.plist
        sudo launchctl load -w /System/Library/LaunchDaemons/ssh.plist

    - name: Generate key pairs
      if: inputs.ssh_keygen
      shell: bash
      run: |
        ssh-keygen -q -t rsa -N '' -f $HOME/.ssh/id_rsa

    - name: Add id_rsa into authorized_keys
      if: inputs.ssh_add_id_rsa_into_authorized_keys
      shell: bash
      run: |
        cat $HOME/.ssh/id_rsa.pub >> $HOME/.ssh/authorized_keys

    - name: Ensure permissions for $HOME/.ssh/authorized_keys to be 0600
      shell: bash
      run: |
        chmod 0600 $HOME/.ssh/authorized_keys
